# Generated by Django 3.0 on 2021-03-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGender',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_gender', models.IntegerField()),
            ],
            options={
                'db_table': 'user_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('cid', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('structure', models.CharField(blank=True, max_length=255, null=True)),
                ('MolecularFormula', models.CharField(blank=True, max_length=255, null=True)),
                ('MolecularWeight', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'chemistry',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=200)),
                ('name', models.FileField(max_length=200, upload_to='resource/%Y/%m/%d/', verbose_name='下载地址')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='CodeImages',
            fields=[
                ('code_images', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('entryname', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundformula', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='teafound.Chemistry')),
            ],
            options={
                'db_table': 'code_images',
            },
        ),
    ]
