# Generated by Django 2.2 on 2021-03-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerosPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(blank=True, max_length=255, null=True)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kda_k', models.IntegerField(blank=True, null=True)),
                ('kda_d', models.IntegerField(blank=True, null=True)),
                ('kda_a', models.IntegerField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('damage_input', models.IntegerField(blank=True, null=True)),
                ('damage_output', models.IntegerField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heros_play',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HerosTemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'heros_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HerosWithIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hp_max', models.FloatField(blank=True, null=True)),
                ('hp_growth', models.FloatField(blank=True, null=True)),
                ('hp_start', models.FloatField(blank=True, null=True)),
                ('mp_max', models.FloatField(blank=True, null=True)),
                ('mp_growth', models.FloatField(blank=True, null=True)),
                ('mp_start', models.FloatField(blank=True, null=True)),
                ('attack_max', models.FloatField(blank=True, null=True)),
                ('attack_growth', models.FloatField(blank=True, null=True)),
                ('attack_start', models.FloatField(blank=True, null=True)),
                ('defense_max', models.FloatField(blank=True, null=True)),
                ('defense_growth', models.FloatField(blank=True, null=True)),
                ('defense_start', models.FloatField(blank=True, null=True)),
                ('hp_5s_max', models.FloatField(blank=True, null=True)),
                ('hp_5s_growth', models.FloatField(blank=True, null=True)),
                ('hp_5s_start', models.FloatField(blank=True, null=True)),
                ('mp_5s_max', models.FloatField(blank=True, null=True)),
                ('mp_5s_growth', models.FloatField(blank=True, null=True)),
                ('mp_5s_start', models.FloatField(blank=True, null=True)),
                ('attack_speed_max', models.FloatField(blank=True, null=True)),
                ('attack_range', models.CharField(blank=True, max_length=255, null=True)),
                ('role_main', models.CharField(blank=True, max_length=255, null=True)),
                ('role_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heros_with_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HerosWithoutIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hp_max', models.FloatField(blank=True, null=True)),
                ('hp_growth', models.FloatField(blank=True, null=True)),
                ('hp_start', models.FloatField(blank=True, null=True)),
                ('mp_max', models.FloatField(blank=True, null=True)),
                ('mp_growth', models.FloatField(blank=True, null=True)),
                ('mp_start', models.FloatField(blank=True, null=True)),
                ('attack_max', models.FloatField(blank=True, null=True)),
                ('attack_growth', models.FloatField(blank=True, null=True)),
                ('attack_start', models.FloatField(blank=True, null=True)),
                ('defense_max', models.FloatField(blank=True, null=True)),
                ('defense_growth', models.FloatField(blank=True, null=True)),
                ('defense_start', models.FloatField(blank=True, null=True)),
                ('hp_5s_max', models.FloatField(blank=True, null=True)),
                ('hp_5s_growth', models.FloatField(blank=True, null=True)),
                ('hp_5s_start', models.FloatField(blank=True, null=True)),
                ('mp_5s_max', models.FloatField(blank=True, null=True)),
                ('mp_5s_growth', models.FloatField(blank=True, null=True)),
                ('mp_5s_start', models.FloatField(blank=True, null=True)),
                ('attack_speed_max', models.FloatField(blank=True, null=True)),
                ('attack_range', models.CharField(blank=True, max_length=255, null=True)),
                ('role_main', models.CharField(blank=True, max_length=255, null=True)),
                ('role_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heros_without_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGender',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_gender', models.IntegerField()),
            ],
            options={
                'db_table': 'user_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodeImages',
            fields=[
                ('code_images', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('entryname', models.CharField(blank=True, max_length=255, null=True)),
                ('compoundformula', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'code_images',
            },
        ),
        migrations.CreateModel(
            name='Heros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hp_max', models.FloatField(blank=True, null=True)),
                ('hp_growth', models.FloatField(blank=True, null=True)),
                ('hp_start', models.FloatField(blank=True, null=True)),
                ('mp_max', models.FloatField(blank=True, null=True)),
                ('mp_growth', models.FloatField(blank=True, null=True)),
                ('mp_start', models.FloatField(blank=True, null=True)),
                ('attack_max', models.FloatField(blank=True, null=True)),
                ('attack_growth', models.FloatField(blank=True, null=True)),
                ('attack_start', models.FloatField(blank=True, null=True)),
                ('defense_max', models.FloatField(blank=True, null=True)),
                ('defense_growth', models.FloatField(blank=True, null=True)),
                ('defense_start', models.FloatField(blank=True, null=True)),
                ('hp_5s_max', models.FloatField(blank=True, null=True)),
                ('hp_5s_growth', models.FloatField(blank=True, null=True)),
                ('hp_5s_start', models.FloatField(blank=True, null=True)),
                ('mp_5s_max', models.FloatField(blank=True, null=True)),
                ('mp_5s_growth', models.FloatField(blank=True, null=True)),
                ('mp_5s_start', models.FloatField(blank=True, null=True)),
                ('attack_speed_max', models.FloatField(blank=True, null=True)),
                ('attack_range', models.CharField(blank=True, max_length=255, null=True)),
                ('role_main', models.CharField(blank=True, max_length=255, null=True)),
                ('role_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heros',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=200)),
                ('name', models.FileField(max_length=200, upload_to='resource/%Y/%m/%d/', verbose_name='下载地址')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
