# Generated by Django 3.0 on 2021-03-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teafound', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeimages',
            old_name='cid',
            new_name='chem_id',
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='cid',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
