# Generated by Django 3.0 on 2021-03-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teafound', '0002_auto_20210315_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='structure',
            field=models.CharField(blank=True, default='seeyou', max_length=255, null=True),
        ),
    ]
