# Generated by Django 3.0 on 2021-03-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teafound', '0004_auto_20210315_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeimages',
            name='chem_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teafound.Chemistry'),
        ),
    ]
