# Generated by Django 3.0 on 2021-03-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teafound', '0005_auto_20210315_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeimages',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeimages',
            name='code_images',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
