# Generated by Django 3.0 on 2021-03-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teafound', '0006_auto_20210315_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeimages',
            name='chem_id',
        ),
    ]
