# Generated by Django 3.0 on 2021-03-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teafound', '0008_auto_20210315_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeimages',
            name='code_images',
            field=models.CharField(default='12', max_length=255, primary_key=True, serialize=False),
        ),
    ]
