# Generated by Django 3.0 on 2021-03-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teafound', '0009_auto_20210315_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeimages',
            name='chem_id',
        ),
        migrations.AddField(
            model_name='codeimages',
            name='cid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
